### ISSUE TITLE
logic is missing

### ISSUE THREAD

**Issue by wiut3476** [awran5/speedTyping#1]
Can't play the game after downloading. The main logic is missing on purpose in ZIP I think. Ready to donate if you provide full version

**Comment by awran5** [comment]
Hello @wiut3476 

Sorry for the late response.. its kinda an old app and I didn't check it for a awhile.. 
Actually it is the full version but I think you just missed that it requires a live server on you local machine in order to run properly.

There are too many ways to set a local server on your PC but the easiest way that I can think of is to use [VS Code](https://code.visualstudio.com/) as a Editor and just install [LiveServer extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer).

If you like, There is another "lite" [React version](https://github.com/awran5/react-one-minute-speed-typing-test-ts) you may find  interesting.

Please let me know if you need any help.
